---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: default
  labels: &labels
    app: pgadmin
    component: deployment
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        envFrom:
        - configMapRef:
            name: pgadmin-configmap
        - secretRef:
            name: pgadmin-secrets
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
      volumes:
      - name: pgadmin-data
        emptyDir: {}