---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: database
  labels:
    app: pgadmin
    component: service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31080
  selector:
    app: pgadmin
    component: deployment