---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pgadmin-secrets
  namespace: database
  labels:
    app: pgadmin
    component: secrets
stringData:
  PGADMIN_DEFAULT_PASSWORD: "pgadmin123"