---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-logs-pvc
  namespace: database
  labels:
    app: postgres
    component: logs-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "local-path"